# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Deploy agntcy AGP components
description: Deploy agntcy AGP components
inputs:
  gateway-image-tag:
    description: 'Set gateway container image version'
    required: false
    default: '0.3.14'
  mcp-proxy-deploy:
    description: 'Deploy MCP proxy'
    required: false
    default: 'false'
  mcp-proxy-image-tag:
    description: 'Set mcp proxy container image version'
    required: false
    default: '0.1.4'
  mcp-server-addr:
    description: 'Set mcp server address'
    required: false
    default: 'http://mcp-server:8000/sse'
  gateway-chart-tag:
    description: 'Set gateway chart version'
    required: false
    default: 'v0.1.4'
  kind-cluster-name:
    description: 'Set kind cluster name where components are deployed'
    required: false
    default: 'agntcy-test'
  kind-cluster-namespace:
    description: 'Set cluster namespace where components are deployed'
    required: false
    default: 'default'

runs:
  using: 'composite'
  steps:
    - name: Create Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: ${{ inputs.kind-cluster-name }}
        wait: 300s

    - name: deploy agntcy AGP
      shell: bash
      env:
        GATEWAY_IMAGE_TAG: ${{ inputs.gateway-image-tag }}
        MCP_PROXY_IMAGE_TAG: ${{ inputs.mcp-proxy-image-tag }}
        MCP_PROXY_DEPLOY: ${{ inputs.mcp-proxy-deploy }}
        MCP_SERVER_ADDR: ${{ inputs.mcp-server-addr }}
        GATEWAY_CHART_TAG: ${{ inputs.gateway-chart-tag }}
        KIND_CLUSTER_NAME: ${{ inputs.kind-cluster-name }}
        KIND_CLUSTER_NAMESPACE: ${{ inputs.kind-cluster-namespace }}
      run: |
        helm upgrade agntcy-agp oci://ghcr.io/agntcy/agp/helm/agp \
          --version $GATEWAY_CHART_TAG \
          --set gw.image.tag="${GATEWAY_IMAGE_TAG}" \
          --set mcpProxy.enabled="${MCP_PROXY_DEPLOY}"
          --set mcpProxy.image.tag="${MCP_PROXY_IMAGE_TAG}" \
          --set mcpProxy.args.mcpServer="${MCP_SERVER_ADDR}" \
          --namespace $KIND_CLUSTER_NAMESPACE \
          --create-namespace \
          --install \
          --wait \
          --wait-for-jobs \
          --timeout "15m"
