# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

slim:
  config:
    tracing:
      log_level: info
      display_thread_names: true
      display_thread_ids: true

    runtime:
      n_cores: 0
      thread_name: "slim-data-plane"
      drain_timeout: 10s

    services:
      slim/0:
        pubsub:
          clients:
            - endpoint: "http://agntcy-slim:46357"
              tls:
                insecure: true
