# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Deploy agntcy components
description: Deploy agntcy components for integration testing
inputs:
  checkout-repository:
    description: 'Checkout AGNTCY repository'
    required: false
    default: 'false'
  checkout-path:
    description: 'Path to checkout AGNTCY repository'
    required: false
    default: ''
  deploy-slim:
    description: 'Deploy slim to a kind cluster'
    required: false
    default: 'false'
  slim-image-tag:
    description: 'Set slim container image version'
    required: false
    default: ''
  slim-chart-tag:
    description: 'Set slim chart version'
    required: false
    default: ''
  deploy-directory:
    description: 'Deploy directory to a kind cluster'
    required: false
    default: 'false'
  directory-image-tag:
    description: 'Set directory container image version'
    required: false
    default: ''
  directory-chart-tag:
    description: 'Set directory chart version'
    required: false
    default: ''
  kind-cluster-name:
    description: 'Set kind cluster name where components are deployed'
    required: false
    default: 'agntcy-test'
  kind-cluster-namespace:
    description: 'Set cluster namespace where components are deployed'
    required: false
    default: 'default'
  github-repository-ref:
    description: 'Set a ref for git checkout'
    required: false
    default: 'main'
  install-kind-dependency:
    description: 'KinD installer'
    required: false
    default: 'false'
  kind-binary-version:
    description: 'Installed KinD version'
    required: false
    default: 'v0.27.0'
  install-taskfile-dependency:
    description: 'Taskfile installer'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Checkout agntcy repository
      if: ${{ inputs.checkout-repository != 'false' }}
      uses: actions/checkout@v4
      with:
        repository: 'agntcy/csit'
        ref: ${{ inputs.github-repository-ref }}
        path: ${{ inputs.checkout-path }}

    - name: Install KinD
      if: ${{ inputs.install-kind-depedency != 'false' }}
      shell: bash
      run: |
        ARCH=""
        if [ $(uname -m) = x86_64 ]; then
          ARCH="amd64"
        elif [ $(uname -m) = aarch64 ]; then
          ARCH="arm64"
        else
          echo "Unkown architecture, abort!"
          exit 1
        fi

        curl -Lo ./kind https://kind.sigs.k8s.io/dl/${{ inputs.kind-binary-version }}/kind-linux-$ARCH

        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Install Taskfile
      if: ${{ inputs.install-taskfile-depedency != 'false' }}
      uses: arduino/setup-task@v2
      with:
        version: 3.x

    - name: Create kind cluster
      shell: bash
      run: |
        task -d ./${{ inputs.checkout-path }} integrations:kind:create \
          KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }}

    - name: Deploy Slim
      if: ${{ inputs.deploy-slim != 'false' }}
      shell: bash
      run: |
        task -d ./${{ inputs.checkout-path }} integrations:slim:test-env:deploy \
          SLIM_IMAGE_TAG=${{ inputs.slim-image-tag }} \
          SLIM_CHART_TAG=${{ inputs.slim-chart-tag }} \
          KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }} \
          HELM_NAMESPACE=${{ inputs.kind-cluster-namespace }}

    - name: Deploy Directory
      if: ${{ inputs.deploy-directory != 'false' }}
      shell: bash
      run: |
        task -d ./${{ inputs.checkout-path }} integrations:directory:test-env:deploy \
          DIRECTORY_IMAGE_TAG=${{ inputs.directory-image-tag }} \
          DIRECTORY_CHART_TAG=${{ inputs.directory-chart-tag }} \
          KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }} \
          HELM_NAMESPACE=${{ inputs.kind-cluster-namespace }}

        task -d ./${{ inputs.checkout-path }} integrations:directory:test-env:network:deploy \
          DIRECTORY_IMAGE_TAG=${{ inputs.directory-image-tag }} \
          DIRECTORY_CHART_TAG=${{ inputs.directory-chart-tag }}
          KIND_CLUSTER_NAME=${{ inputs.kind-cluster-name }} \
