# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

vars:
  KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "agntcy-test" }}'

  ## Image config
  IMAGE_REPO: '{{ .IMAGE_REPO | default "ghcr.io/agntcy" }}'
  GATEWAY_IMAGE_TAG: '{{ .GATEWAY_IMAGE_TAG | default "0.3.0" }}'
  DIRECTORY_IMAGE_TAG: '{{ .DIRECTORY_IMAGE_TAG | default "v0.1.2" }}'

  IMAGE_BAKE_OPTS: '{{ .IMAGE_BAKE_OPTS | default "--set *.platform=linux/arm64" }}'
  TEST_APP_TAG: '{{ .TEST_APP_TAG | default "v0.0.1" }}'

  AZURE_OPENAI_API_KEY: '{{ .AZURE_OPENAI_API_KEY | default "" }}'
  AZURE_OPENAI_ENDPOINT: '{{ .AZURE_OPENAI_ENDPOINT | default "" }}'

  HELM_NAMESPACE: '{{ .HELM_NAMESPACE | default "default" }}'

tasks:
  kind:create:
    desc: Create kind cluster
    cmds:
      - kind create cluster --name {{.KIND_CLUSTER_NAME}} --wait 60s || true
      - kubectl cluster-info --context kind-{{.KIND_CLUSTER_NAME}}

  kind:destroy:
    desc: Destroy kind cluster
    cmds:
      - kind delete cluster --name {{.KIND_CLUSTER_NAME}}

  k8s:port-forward:setup:directory:
    internal: true
    cmds:
      - kubectl port-forward svc/agntcy-dir-apiserver -n {{ .HELM_NAMESPACE }} 8888 &
      - sleep 1

  k8s:port-forward:teardown:directory:
    internal: true
    cmds:
      - kill -9 $(ps aux | grep port-forward | grep agntcy-dir-apiserver | awk '{print $2}') || true

  k8s:port-forward:setup:gateway:
    internal: true
    cmds:
      - kubectl port-forward svc/agntcy-agp -n {{ .HELM_NAMESPACE }} 46357 &
      - sleep 1

  k8s:port-forward:teardown:gateway:
    internal: true
    cmds:
      - kill -9 $(ps aux | grep port-forward | grep agntcy-agp | awk '{print $2}') || true

  test:env:directory:deploy:
    desc: Deploy Agntcy directory test env
    vars:
      REGCRED_CREATE: '{{ .REGCRED_CREATE | default "false" }}'
    cmds:
      - |
        helm dependency build ./agntcy-dir/components/helm
        helm upgrade agntcy-dir \
          ./agntcy-dir/components/helm \
          --set dir.apiserver.image.tag="{{ .DIRECTORY_IMAGE_TAG }}" \
          --set regcred.create="{{ .REGCRED_CREATE }}" \
          --namespace {{ .HELM_NAMESPACE }} \
          --create-namespace \
          --install \
          --wait \
          --wait-for-jobs \
          --timeout "15m"

  test:env:directory:cleanup:
    desc: Remove agntcy directory test env
    cmds:
      - helm delete --namespace {{ .HELM_NAMESPACE }} agntcy-dir

  test:env:gateway:deploy:
    desc: Deploy agntcy gateway test env
    cmds:
      - |
        helm dependency build ./agntcy-agp/components/helm
        helm upgrade agntcy-agp \
          ./agntcy-agp/components/helm \
          --set agp.image.tag="{{ .GATEWAY_IMAGE_TAG }}" \
          --namespace {{ .HELM_NAMESPACE }} \
          --create-namespace \
          --install \
          --wait \
          --wait-for-jobs \
          --timeout "15m"

  test:env:gateway:cleanup:
    desc: Remove agent gateway test env
    cmds:
      - helm delete --namespace {{ .HELM_NAMESPACE }} agntcy-agp

  build:gateway:agentic-apps:
    desc: Build agentic containers
    dir: ./agntcy-agp/agentic-apps
    cmds:
      - IMAGE_TAG={{ .TEST_APP_TAG }} docker buildx bake {{ .IMAGE_BAKE_OPTS }} --load

  test:directory:
    desc: Directory test
    cmds:
      - task: k8s:port-forward:setup:directory
      - defer: { task: k8s:port-forward:teardown:directory }
      - defer: { task: manifests:cleanup }
      - IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./agntcy-dir/tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v

  test:directory:compiler:
    desc: Agntcy compiler test
    cmds:
      - docker pull {{.IMAGE_REPO}}/dir-ctl:{{.DIRECTORY_IMAGE_TAG}}
      - IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./agntcy-dir/tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 10m -timeout 10m -ginkgo.v -ginkgo.focus "agent compilation"

  test:directory:push:
    desc: Directory agent push test
    cmds:
      - task: k8s:port-forward:setup:directory
      - defer: { task: k8s:port-forward:teardown:directory }
      - defer: { task: manifests:cleanup }
      - IMAGE_REPO={{.IMAGE_REPO}} DIRECTORY_IMAGE_TAG={{.DIRECTORY_IMAGE_TAG}} go test ./agntcy-dir/tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "agent push and pull"

  test:autogen-agent:run:
    internal: true
    cmds:
      - |
        hostNetFlag=""
        hostMachine=http://host.docker.internal:46357
        unameOut=$(uname -s)
        case ${unameOut} in
            Linux*)
              hostMachine=http://127.0.0.1:46357
              hostNetFlag="--net=host"
            ;;
            Darwin*)
              hostMachine=http://host.docker.internal:46357
            ;;
            *)
        esac
        echo "gw host: ${hostMachine}"

        docker run -d --rm \
        -e AZURE_OPENAI_API_KEY={{.AZURE_OPENAI_API_KEY}} \
        -e AZURE_OPENAI_ENDPOINT={{.AZURE_OPENAI_ENDPOINT}} \
        ${hostNetFlag} \
        --name autogen-agent \
        {{ .IMAGE_REPO }}/csit/test-autogen-agent:{{ .TEST_APP_TAG }} \
        poetry run python autogen_agent.py -g ${hostMachine}

  test:autogen-agent:remove:
    internal: true
    cmds:
      - docker stop $(docker ps -a --no-trunc --filter name=^/autogen-agent$ -q)

  test:gateway:
    desc: Gateway test
    vars:
      REMOVE_CONTAINERS: '{{ .REMOVE_CONTAINERS | default "true" }}'
    cmds:
      - task: k8s:port-forward:setup:gateway
      - defer: { task: k8s:port-forward:teardown:gateway }
      - task: test:autogen-agent:run
      - defer: { task: test:autogen-agent:remove }
      - docker pull {{ .IMAGE_REPO }}/csit/test-langchain-agent:{{ .TEST_APP_TAG }}
      - REMOVE_CONTAINERS={{.REMOVE_CONTAINERS}} IMAGE_REPO={{.IMAGE_REPO}} TEST_APP_TAG={{.TEST_APP_TAG}} go test ./agntcy-agp/tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v

  version:
    desc: Get version
    cmds:
      - git describe --tags --match "v*" | cut -c 2-
