# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

includes:
  gateway:
    taskfile: ./agntcy-agp/Taskfile.yml
    dir: ./agntcy-agp
    excludes: [ default ]
    vars:
      KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME }}'
      GATEWAY_IMAGE_TAG: '{{ .GATEWAY_IMAGE_TAG }}'
      GATEWAY_CHART_TAG: '{{ .GATEWAY_CHART_TAG }}'
      HELM_NAMESPACE: '{{ .HELM_NAMESPACE }}'

  directory:
    taskfile: ./agntcy-dir/Taskfile.yml
    dir: ./agntcy-dir
    excludes: [ default ]
    vars:
      KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME }}'
      DIRECTORY_IMAGE_TAG: '{{ .DIRECTORY_IMAGE_TAG }}'
      DIRECTORY_CHART_TAG: '{{ .DIRECTORY_CHART_TAG }}'
      HELM_NAMESPACE: '{{ .HELM_NAMESPACE }}'

  apps:
    taskfile: ./agntcy-apps/Taskfile.yml
    dir: ./agntcy-apps
    excludes: [ default ]
    vars:
      WFSM_BIN_VERSION: '{{ .WFSM_BIN_VERSION }}'

  wfsm:
    taskfile: ./agntcy-wfsm/Taskfile.yml
    dir: ./agntcy-wfsm
    excludes: [ default ]
    vars:
      WFSM_BIN_VERSION: '{{ .WFSM_BIN_VERSION }}'

vars:
  KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "agntcy-test" }}'

tasks:
  kind:create:
    desc: Create kind cluster
    cmds:
      - kind create cluster --name {{.KIND_CLUSTER_NAME}} --wait 60s || true
      - kubectl cluster-info --context kind-{{.KIND_CLUSTER_NAME}}

  kind:destroy:
    desc: Destroy kind cluster
    cmds:
      - kind delete cluster --name {{.KIND_CLUSTER_NAME}}

  version:
    desc: Get version
    cmds:
      - git describe --tags --match "v*" | cut -c 2-

  default:
    cmd: task -l