# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

includes:
  integrations:
    taskfile: ./integrations/Taskfile.yml
    dir: ./integrations
    excludes: [default]
    vars:
      DIRECTORY_IMAGE_TAG: '{{ .DIRECTORY_IMAGE_TAG }}'
      DIRECTORY_CHART_TAG: '{{ .DIRECTORY_CHART_TAG }}'
      SLIM_IMAGE_TAG: '{{ .SLIM_IMAGE_TAG }}'
      SLIM_CHART_TAG: '{{ .SLIM_CHART_TAG }}'

  samples:
    taskfile: ./samples/Taskfile.yml
    dir: ./samples
    excludes: [default]

  benchmarks:
    taskfile: ./benchmarks/Taskfile.yml
    dir: ./benchmarks
    excludes: [default]

tasks:
  default:
    cmd: task -l
