# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

slim:
  config:
    tracing:
      log_level: debug
      display_thread_names: true
      display_thread_ids: true

    runtime:
      n_cores: 0
      thread_name: "slim-data-plane"
      drain_timeout: 10s

    services:
      slim/0:
        pubsub:
          servers:
          - endpoint: "0.0.0.0:46357"
            tls:
              cert_file: "/etc/certs/tls.crt"
              key_file: "/etc/certs/tls.key"

              client_ca_file: "/etc/certs/ca.crt"

          clients: []

  extraVolumes:
    - name: certs
      secret:
        secretName: mtls-server-tls

  extraVolumeMounts:
    - name: certs
      mountPath: "/etc/certs"
      readOnly: true