# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

vars:
  KIND_CLUSTER_NAME: '{{ .KIND_CLUSTER_NAME | default "agntcy-test" }}'

  ## Image config
  IMAGE_REPO: '{{ .IMAGE_REPO | default "ghcr.io/agntcy" }}'
  GATEWAY_IMAGE_TAG: '{{ .GATEWAY_IMAGE_TAG | default "0.3.15" }}'
  MCP_PROXY_IMAGE_TAG: '{{ .MCP_PROXY_IMAGE_TAG | default "0.1.4" }}'
  GATEWAY_CHART_TAG: '{{ .GATEWAY_CHART_TAG | default "v0.1.4" }}'

  IMAGE_BAKE_OPTS: '{{ .IMAGE_BAKE_OPTS | default "--set *.platform=linux/arm64" }}'
  LANGCHAIN_APP_TAG: '{{ .LANGCHAIN_APP_TAG | default "v0.0.9" }}'
  AUTOGEN_APP_TAG: '{{ .AUTOGEN_APP_TAG | default "v0.0.9" }}'

  AZURE_OPENAI_API_KEY: '{{ .AZURE_OPENAI_API_KEY | default "" }}'
  AZURE_OPENAI_ENDPOINT: '{{ .AZURE_OPENAI_ENDPOINT | default "" }}'

  HELM_NAMESPACE: '{{ .HELM_NAMESPACE | default "default" }}'
  MCP_PROXY_DEPLOY: '{{ .MCP_PROXY_DEPLOY | default "true" }}'
  LLAMAINDEX_TIME_AGENT_TAG: '{{ .LLAMAINDEX_TIME_AGENT_TAG | default "0.1.1" }}'
  MCP_SERVER_TIME_TAG: '{{ .MCP_SERVER_TIME_TAG | default "0.1.1" }}'

  REMOVE_CONTAINERS: '{{ .REMOVE_CONTAINERS | default "true" }}'

  RUNNER_TYPE: '{{ .RUNNER_TYPE | default "docker" }}'

tasks:
  k8s:port-forward:setup:
    internal: true
    cmds:
      - kubectl port-forward svc/agntcy-agp -n {{ .HELM_NAMESPACE }} 46357 &
      - sleep 1

  k8s:port-forward:teardown:
    internal: true
    cmds:
      - kill -9 $(ps aux | grep port-forward | grep agntcy-agp | awk '{print $2}') || true

  test-env:deploy:
    desc: Deploy agntcy gateway test env
    cmds:
      - |
        helm upgrade agntcy-agp \
          oci://{{ .IMAGE_REPO }}/agp/helm/agp \
          --version {{ .GATEWAY_CHART_TAG }} \
          --set gw.image.tag="{{ .GATEWAY_IMAGE_TAG }}" \
          --set mcpProxy.image.tag="{{ .MCP_PROXY_IMAGE_TAG }}" \
          --set mcpProxy.enabled="{{ .MCP_PROXY_DEPLOY }}" \
          --namespace {{ .HELM_NAMESPACE }} \
          --create-namespace \
          --install \
          --wait \
          --wait-for-jobs \
          --timeout "15m"

  test-env:cleanup:
    desc: Remove agent gateway test env
    cmds:
      - |
        helm delete --namespace {{ .HELM_NAMESPACE }} agntcy-agp

  build:agentic-apps:
    desc: Build agentic containers
    dir: ./agentic-apps
    cmds:
      - IMAGE_TAG={{ .LANGCHAIN_APP_TAG }} docker buildx bake {{ .IMAGE_BAKE_OPTS }} --load

  test:sanity:
    desc: Sanity gateway test
    cmds:
      - NAMESPACE={{.HELM_NAMESPACE}} IMAGE_REPO={{.IMAGE_REPO}} LANGCHAIN_APP_TAG={{.LANGCHAIN_APP_TAG}} AUTOGEN_APP_TAG={{.AUTOGEN_APP_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "Agntcy gateway sanity test"

  test:mcp-server:
    desc: Test MCP over AGP
    cmds:
      - NAMESPACE={{.HELM_NAMESPACE}} IMAGE_REPO={{.IMAGE_REPO}} MCP_SERVER_TIME_TAG={{.MCP_SERVER_TIME_TAG}} LLAMAINDEX_TIME_AGENT_TAG={{.LLAMAINDEX_TIME_AGENT_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "MCP over AGP test"

  test:mcp-server:agp-native:
    desc: Test AGP native MCP server
    cmds:
      - NAMESPACE={{.HELM_NAMESPACE}} IMAGE_REPO={{.IMAGE_REPO}} MCP_SERVER_TIME_TAG={{.MCP_SERVER_TIME_TAG}} LLAMAINDEX_TIME_AGENT_TAG={{.LLAMAINDEX_TIME_AGENT_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "AGP native MCP server"

  test:mcp-server:mcp-proxy:
    desc: Test MCP server via MCP proxy
    cmds:
      - NAMESPACE={{.HELM_NAMESPACE}} IMAGE_REPO={{.IMAGE_REPO}} MCP_SERVER_TIME_TAG={{.MCP_SERVER_TIME_TAG}} LLAMAINDEX_TIME_AGENT_TAG={{.LLAMAINDEX_TIME_AGENT_TAG}} go test ./tests -v -failfast -test.v -test.paniconexit0 -ginkgo.timeout 30m -timeout 30m -ginkgo.v -ginkgo.focus "MCP server via MCP proxy"

  default:
    cmd: task -l