# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true

tasks:
  dependencies:
    internal: true
    desc: Install dependencies
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - poetry install --no-root

  run:crew:
    desc: Run application main
    dir: '{{.USER_WORKING_DIR}}'
    deps:
      - dependencies
    cmds:
      - poetry run python -m model.crew

  run:test-deepeval:
    internal: true
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - poetry run python -m tests._deepeval

  run:test-ragas:
    internal: true
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - poetry run python -m tests._ragas

  run:test:
    desc: Run tests
    dir: '{{.USER_WORKING_DIR}}'
    deps:
      - dependencies
    cmds:
      - task: run:test-deepeval
      - task: run:test-ragas
