# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

name: Setup Python Environment
description: setup environment to build/test/lint python applications
inputs:
  py-version:
    description: 'Python version to install'
    required: false
    default: "3.12"
  py-package-manager:
    description: 'Python package manager to use'
    required: false
    default: "poetry"
  py-poetry-version:
    description: 'Poetry version to use'
    required: false
    default: "1.7.1"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py-version }}

    - name: Load cached Poetry Binary
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ inputs.py-poetry-version }}

    - name: Install Poetry
      shell: bash
      run: |
        if [[ -f ~/.local/bin/poetry ]]; then
          echo "Poetry already installed"
        else
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=${{ inputs.py-poetry-version }} python3 -
        fi

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${HOME}/.local/bin" sh

    - name: Load cached venv
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Update GITHUB_PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
