# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: test-remote-workflow-dispatch-trigger
on:
  workflow_dispatch:

jobs:
    trigger-integration-workflow:
        runs-on: ubuntu-latest
        permissions: write-all # TODO: Find the correct permission or create PAT token
        steps:
        - name: Repository Dispatch
          uses: actions/github-script@v7
          with:
            script: |
                await github.rest.actions.createWorkflowDispatch({
                    owner: 'agntcy',
                    repo: 'csit',
                    workflow_id: 'test-integrations.yaml',
                    ref: 'feat/gh-action-repository-dispatch',
                    inputs: {
                        override_slim_image_tag: '0.3.11',
                        override_directory_image_tag: 'v0.2.1',
                    },
                });
            debug: true